
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "11.1.1-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "9.2.0"

[[constraint]]
  name = "github.com/JamesClonk/vultr"
  version = "1.13.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.20"

[[constraint]]
  branch = "master"
  name = "github.com/decker502/dnspod-go"

[[constraint]]
  name = "github.com/dnsimple/dnsimple-go"
  version = "0.14.0"

[[constraint]]
  name = "github.com/edeckers/auroradnsclient"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/exoscale/egoscale"

[[constraint]]
  branch = "master"
  name = "github.com/miekg/dns"

[[constraint]]
  branch = "master"
  name = "github.com/ovh/go-ovh"

[[constraint]]
  branch = "master"
  name = "github.com/rainycape/memcache"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/timewasted/linode"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/ns1/ns1-go.v2"

[[constraint]]
  name = "gopkg.in/square/go-jose.v1"
  version = "1.1.0"
